/// A row in the OVN Southbound `Gateway_Chassis` table: one candidate chassis,
/// with a priority, for a `chassisredirect` port binding.
///
/// `OVNSB`-prefixed because `Gateway_Chassis` names a table in both databases —
/// see `OVNGatewayChassis` for the Northbound row a client writes. The
/// difference to watch is `chassis`: Northbound the column is `chassis_name`, a
/// plain string, whereas here it is a real weak reference into `OVNChassis`,
/// which is what makes a Southbound row's chassis read as unset once that
/// chassis is deleted. `OVNPortBinding.gateway_chassis` references these rows.
///
/// Read-only: ovn-northd owns these rows, so there is no create/update path on
/// `OVNManager` and no public initializer.
public struct OVNSBGatewayChassis: Codable, Sendable {
    public let uuid: String?
    /// The row's name, generated by ovn-northd from the router port and chassis
    /// it was created for.
    public let name: String
    /// UUID reference to the `OVNChassis` this candidate names. A weak
    /// reference, so it reads as nil once that chassis is gone — including
    /// after `deleteChassis(named:)`.
    public let chassis: String?
    /// Priority within the port's candidate set (0–32767); the highest-priority
    /// reachable chassis is the active gateway.
    public let priority: Int
    public let options: [String: String]?
    public let external_ids: [String: String]?

    private enum CodingKeys: String, CodingKey {
        case uuid = "_uuid"
        case name, chassis, priority, options, external_ids
    }
}
